### ISSUE TITLE
How to make a direct command line

### ISSUE THREAD

**Issue by swatky** [TacoAnime69/nh-pdf-downloader#10]
How can I write a direct command line to download certain nuclear code?
For example:
nh-pdf-downloader -123456
![image](https://user-images.githubusercontent.com/40281950/106622447-57d17300-6552-11eb-9b04-046de209dee3.png)
I renamed the exe name to "nhpdf"

I want to put this command line in a project that I have on nodejs.
Example the another command base:
exec('hentai --id=' + nuclear+ ` -P mantap.pdf -o ./hentong/${nuclear}.pdf --format `+ `${nuclear}.pdf`, (error, stdout, stderr) =>

**Comment by TacoAnime69** [comment]
Hi! Sorry for the late response, I forgot to get back to this. 

To be honest, I'm not exactly sure how I'd go about that. What I would try is compiling the program using pyinstaller (see readme.md) and adding that as an environment variable to Windows (I think I left that somewhere in the FAQ).
Sadly on Windows, getting pyinstaller to work on just command line can be... a bit challenging. I recommend using a dev/python environment (such as Anaconda) to compile the program. Let me know if you find a better solution.

Best of luck!

**Comment by gabrielwsy** [comment]
> Hi! Sorry for the late response, I forgot to get back to this.
> 
> To be honest, I'm not exactly sure how I'd go about that. What I would try is compiling the program using pyinstaller (see readme.md) and adding that as an environment variable to Windows (I think I left that somewhere in the FAQ).
> Sadly on Windows, getting pyinstaller to work on just command line can be... a bit challenging. I recommend using a dev/python environment (such as Anaconda) to compile the program. Let me know if you find a better solution.
> 
> Best of luck!

Hello, I thought of something, create an argument for the application to read the nuclear code, for example
nhpdf -id 123456
the -id argument inserts the code, but I need to know how to rename the file to a short name, so that the bot can read and send through a sendfile ().
Can you understand what I'm thinking?
Sorry for the delay, I had other issues to resolve.

**Comment by TacoAnime69** [comment]
Oh okay, I understand. That's going to take some code writing on my part. Right now, there's no way to do that, but it shouldn't take long to implement. I'll let you know when it's done.

**Comment by gabrielwsy** [comment]
> Oh okay, I understand. That's going to take some code writing on my part. Right now, there's no way to do that, but it shouldn't take long to implement. I'll let you know when it's done.

Good, thank you very much for your attention and understanding, I will be waiting.
Excuse me for any inconvenience.
