### ISSUE TITLE
"Errno 22" Invalid Argument 

### ISSUE THREAD

**Issue by jruwe** [TacoAnime69/nh-pdf-downloader#9]
Hi, I really enjoy the program! I am just having one small issue, on a few albums I am encountering the issue "Errno 22" Invalid Argument and the program fails, I think it has something to do with windows not recognizing a few characters the album (214763) has which are, | < and >. I don't have much coding experience so I am not sure how to fix this but look forward to hearing back.

Running Windows 10 64bit  Python ver. 3.9

![Errno 22](https://user-images.githubusercontent.com/76863062/103471027-525cef00-4d40-11eb-9153-9c22ece5eb93.jpg)

**Comment by jruwe** [comment]
I forgot to add, it creates a temp folder with all the images but doesn't compile and create the pdf. also a problem with 218045.

**Comment by TacoAnime69** [comment]
Hello! Thank you for submitting your issue. Since the change was very small, I've pushed a change directly to master branch. I tested it with the number you provided and it's now working for me. Let me know if you encounter any other problems!
-Taco
